[".config/lf/lfcd.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/gokcehan/lf/master/etc/lfcd.sh"
    refreshPeriod = "168h"
[".antidote"]
    type = "git-repo"
    url = "https://github.com/mattmc3/antidote.git"
    refreshPeriod = "168h"
    [".antidote".clone]
    args = ["--depth=1"]
["bin/zellij"]
    type = "file"
    url = "https://github.com/zellij-org/zellij/releases/latest/download/zellij-x86_64-unknown-linux-musl.tar.gz"
    executable = true
    refreshPeriod = "168h"
    ["bin/zellij".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "zellij"]
