email = "brendon.soto@gmail.com"

[alacritty.tokyo_night.day]
primary.background = "'0xe1e2e7'"
primary.foreground = "'0x3760bf'"

normal.black = "'0xe9e9ed'"
normal.red = "'0xf52a65'"
normal.green = "'0x587539'"
normal.yellow = "'0x8c6c3e'"
normal.blue = "'0x2e7de9'"
normal.magenta = "'0x9854f1'"
normal.cyan = "'0x007197'"
normal.white = "'0x6172b0'"

bright.black = "'0xa1a6c5'"
bright.red = "'0xf52a65'"
bright.green = "'0x587539'"
bright.yellow = "'0x8c6c3e'"
bright.blue = "'0x2e7de9'"
bright.magenta = "'0x9854f1'"
bright.cyan = "'0x007197'"
bright.white = "'0x3760bf'"

indexed_colors.sixteen = "'0xb15c00'"
indexed_colors.seventeen = "'0xc64343'"

[alacritty.tokyo_night.storm]
primary.background = "'0x24283b'"
primary.foreground = "'0xc0caf5'"

normal.black = "'0x1D202F'"
normal.red = "'0xf7768e'"
normal.green = "'0x9ece6a'"
normal.yellow = "'0xe0af68'"
normal.blue = "'0x7aa2f7'"
normal.magenta = "'0xbb9af7'"
normal.cyan = "'0x7dcfff'"
normal.white = "'0xa9b1d6'"

bright.black = "'0x414868'"
bright.red = "'0xf7768e'"
bright.green = "'0x9ece6a'"
bright.yellow = "'0xe0af68'"
bright.blue = "'0x7aa2f7'"
bright.magenta = "'0xbb9af7'"
bright.cyan = "'0x7dcfff'"
bright.white = "'0xc0caf5'"

indexed_colors.sixteen = "'0xff9e64'"
indexed_colors.seventeen = "'0xdb4b4b'"

