[".config/lf/lfcd.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/gokcehan/lf/master/etc/lfcd.sh"
    refreshPeriod = "168h"
[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    exact = true
    [".oh-my-zsh".clone]
        args = ["--depth=1"]
    [".oh-my-zsh".pull]
        args = ["--ff-only"]
[".config/shell/zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/shell/zsh/custom/plugins/zsh-completions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/shell/zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/shell/zsh/custom/plugins/zsh-vi-mode"]
    type = "archive"
    url = "https://github.com/jeffreytse/zsh-vi-mode/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/share/fonts/hack"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/hack.zip"
    exact = true
    refreshPeriod = "168h"
{{ if eq .chezmoi.os "linux" -}}
[".local/bin/zellij"]
    type = "file"
    url = "https://github.com/zellij-org/zellij/releases/latest/download/zellij-x86_64-unknown-linux-musl.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/zellij".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "zellij"]
[".local/bin/xplr"]
    type = "file"
    url = "https://github.com/sayanarijit/xplr/releases/latest/download/xplr-linux.tar.gz"
    exact = true
    executable = true
    refreshPeriod = "168h"
    [".local/bin/xplr".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "xplr"]
[".local/bin/broot"]
    type = "file"
    url = "https://dystroy.org/broot/download/x86_64-linux/broot"
    exact = true
    executable = true
    refreshPeriod = "168h"
[".asdf"]
    type = "git-repo"
    url = "https://github.com/asdf-vm/asdf.git"
    exact = true
    refreshPeriod = "168h"
{{ if eq .chezmoi.osRelease.id "solus" -}}
[".local/bin/gitui"]
    type = "archive-file"
    url = "https://github.com/extrawurst/gitui/releases/latest/download/gitui-linux-musl.tar.gz"
    refreshPeriod = "168h"
    executable = true
    path = "./gitui"
{{ end -}}
{{ end -}}
