---
# To set DIR: DIR=$HOME/Documents tmuxp load test
session_name: "${SESH_NAME}"
start_directory: "${DIR}"
windows:
  - window_name: dev
  - window_name: build+test
    layout: even-horizontal
    panes:
      - blank
      - blank
