---
# To set DIR: DIR=$HOME/Documents tmuxp load test
session_name: default
start_directory: "${DIR}"
windows:
  - window_name: dev
  - window_name: build+test
  # This portion is broken -- results in a pane w/ a width of 1 or 2 columns
  #   layout: main-vertical
  #   panes:
  #     - blank
  #     - blank
