# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# See if this reduces the frequency of "Executing ... timed out" errors
command_timeout = 1000

# Symbols I like:
#       ﴪ  ﯤ      ﳝ ﳟ  ﰌ ﰑ ﲅ  

# Disable/hide AWS info
[aws]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
format = " "
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

# Trying to improve performance
# kudos: https://github.com/starship/starship/issues/4305#issuecomment-1222882244
[git_status]
ignore_submodules = true
untracked = ""

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
